//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCVEntities : DbContext
    {
        public DbCVEntities()
            : base("name=DbCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ABOUT> TBL_ABOUT { get; set; }
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_CERTIFICATES> TBL_CERTIFICATES { get; set; }
        public virtual DbSet<TBL_COMMUNICATION> TBL_COMMUNICATION { get; set; }
        public virtual DbSet<TBL_EDUCATION> TBL_EDUCATION { get; set; }
        public virtual DbSet<TBL_EXPERIENCES> TBL_EXPERIENCES { get; set; }
        public virtual DbSet<TBL_HOBBY> TBL_HOBBY { get; set; }
        public virtual DbSet<TBL_SKILLS> TBL_SKILLS { get; set; }
        public virtual DbSet<TBL_SOCIAL> TBL_SOCIAL { get; set; }
    }
}
