//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EXPERIENCES
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Subheading { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
    }
}
